### ISSUE TITLE
Share ANNIS visualizers as web service without front end

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#107]
I should be possible to call a visualizer for a certain corpus from a certain server and get the visualization back for embedding e.g. in an i-frame in an external website. This is particularly useful for document visualizations, as a project website can have a list of the documents in a corpus and allow users to read an ANNIS-generated output as a running text without having to send a query or work with the more complex ANNIS interface. 

This should work something like a YouTube embed, where the calling website has to specify a server, and either an AQL query + visualizer to show or in case of document visualizations some kind of stable reference to the document. This kind of reference should stay stable even if the corpus is later reimported, so it would be better to use corpus and document names or metadata and not IDs in the database.

**Comment by thomaskrause** [comment]
The current develop version has the new "share" feature which allows to share the visualization of a specific match.

This is implemented in a general way: 
the embedded visualizer only gets the URL where to fetch the Salt from (the `embedded_salt` parameter) and the information it needs to fill out the visualizer configuration. This URL can be a call to the query service for a specific match (http://korpling.github.io/ANNIS/doc/interfaceannis_1_1service_1_1_query_service.html#a7aecc4f056f9b7df21c85851027ae831) or a static file on some web-server. It's only important that the URL is reachable from the Web-server (thus using "localhost" as REST service URL actually works).

If there the `embedded_interface` parameter exists this is used to show a link which leads back to ANNIS.

**Comment by amir-zeldes** [comment]
I like this idea a lot. One minor typo for the share message:

"Chose the visualization to share" > "Choose"

**Comment by thomaskrause** [comment]
I added some documentation how to use this feature under:

http://korpling.github.io/ANNIS/doc-develop/embed.html
