### ISSUE TITLE
User defined corpus groups (sets) in Kickstarter

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#211]
Currently, user defined corpus groups are saved per-user. However in most Kickstarter scenarios, no user management has been set up. This means that Kickstarter users effectively can't use the 'corpus set' feature (which replaces the old favorites/more corpora division). 

In the future, Kickstarter should have no 'login' button (see #204 ). Maybe a sort of 'dummy' user can be set up for kickstarter, which is automatically logged in and also used to save preferences such as corpus groups.

**Comment by amir-zeldes** [comment]
Actually, as of 3.3.6, corpus sets persist in Kickstarter, but since the user is not 'logged in', the right click functionality to add a corpus to a set is disabled. This should either be enabled, or we should scrap this idea and close the issue.

**Comment by thomaskrause** [comment]
Mh, is this feature really necessary for the Kickstarter? I assume people don't have that large instances with a huge number of corpora in the Kickstarter and all of them they also imported by theirself (thus they know the names).

**Comment by amir-zeldes** [comment]
Agreed. Closing this if that's ok for everyone.
