### ISSUE TITLE
Embedding visualizations in external web pages

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#226]
It would be very useful to embed ANNIS visualizers in external web pages, similar to a YouTube or Google Maps embed. The application would be for instance to have a list of documents from a corpus on the corpus project page and be able to directly browse the documents without seeing the 'scary' ANNIS query interface. Because document browsing is a major application, it would be good to be able to embed the document list view as well (the document tab normally shown when clicking on a corpus document icon).

The following possibilities should be supported with the specified parameters:

1. Embedding a visualizer: The embedded element specifies the relevant ANNIS server's URL, a corpus name, a visualizer name, triggering namespace (optional) its mappings (optional) and either: 

    a. An AQL query, context size and the result number (e.g. 'give me the tree visualizer for NS tiger, node_key:mycat, and show the tree for search result 3 of the query mycat="NP" with +-5 tokens on either side)

    b. A document name (fully qualified path with subcorpora, since document names can repeat in different subcorpora), e.g. 'give me pcc2 >11299, show the htmldoc visualizer with the mapping config:infstr).

    The second use case is much more likely to be useful, so if a. is more difficult we can start with b.

2. Embedding the document list: The document list can be embedded in a similar way, except only a corpus is specified. The configuration of the document list can initially be retrieved from the DB (i.e. what metadata to show, what to sort by). In a later step we can think of allowing a different configuration controlled by the embedding element. The arguments for the document list are the server URL and the corpus name to generate the list for. Once the list is generated, the documents can be clicked on and opened either in a new tab or within the same browser window (then pressing 'back' will lead back to the page with the embedded list).

In both cases above, there should be some indication that the information is coming from ANNIS ("powered by ANNIS" and a small icon or something similar) and there should be some link to the ANNIS server the data is coming from, so users can search within the data using the full interface.

**Comment by zangsir** [comment]
[issue#226, 1b functionality added on Pull Request #388] A new method (evaluateFragmentVis() ) is created in SearchUI class for parsing URL call parameters and displaying the htmldoc visualization view of a requested document in the corpus. This functionality is realized by first parsing the url query parameters of corpus name(c), visualizer (vis=htmldoc), stylesheet name(sty), document name(doc) (e.g., #c=shenoute.a22, vis=htmldoc, doc=YA421-428, sty=dipl, in base64), and directly calling the HTMLVis.createComponent() method. This creates and returns a Panel and the resulting panel containing the htmldoc visualization of requested document is then displayed (css style is correctly applied). Meanwhile a notification is given showing the parameter values (corpus, document, visualization, stylesheets) of the url call. The result should be exactly the same as clicking the document visualization in DocBrowser.

**Comment by amir-zeldes** [comment]
This is currently only usable with the HTML visualizer, so the parameter 'vis' is a dummy parameter at this point. Ultimately it could be useful to extend this to other document visualizers. There has been no demand for embedding query results without the interface (#226 1.b) and document list fetching has been realized over the REST API, so I will close this issue as soon as the Pull Request is merged, and open a new issue for the extension to other visualizers (not a high priority, just so we don't forget about the vis parameter being limited).

**Comment by thomaskrause** [comment]
I think we can re-use the issue #107 for the purpose of tracking the more general implementation.
