### ISSUE TITLE
Add discourse view based on annotations instead of tokens

### ISSUE THREAD

**Issue by thomaskrause** [korpling/ANNIS#24]
It should be possible to use the discourse view to view all annotations from a certain layer instead of the tokens. This is mainly a feature request from Falko right now, so you can see the whole document's Target Hypothesis (ZH1 etc.) as a coherent text. We should allow the user to configure the visualization in the resolver specifying the annotation layer to output (default is tok: the discourse view we have now). The visualizer should then output all annotations of that type for that document in plain text, ordered by the elements left token index and then by right token index (in principle it's possible to display nested annotations this way, though it would look terrible).

---

Imported from Launchpad using lp2gh.
- date created: 2011-07-11T14:22:12Z
- owner: amir-zeldes
- assignee: annis
- the launchpad url was https://bugs.launchpad.net/bugs/808808
## UPDATE: Dealing with multiple segmentations

In corpora with multiple segmentation, a 'fake' token layer is used that is often empty, causing the discourse visualizer to display nothing. In some cases, especially historical corpora, it is possible to use this feature request to solve the problem: instead of tokens we can configure the visualization to show "dipl" or "norm" spans. Note that this is not the same as issue #50, which deals with displaying _additional_ annotations on top of the layer used for the discourse view's base text.

For dialogue corpora, we will want to use multiple segmentations to create the discourse view, meaning ideally it should be possible to use _multiple_ annotation layers as base text for the visualizer (potentially this can be implemented in a second step). The desired behavior is as follows, based on a dialogue scenario:

Imagine the document contains two speaker transcription layers, spk1 and spk2, which overlap:

<table>
<tr>
<td>spk1:</td><td>This</td><td>is</td><td>an</td><td>ex</td><td>ample</td><td>.</td><td> </td><td>Yes</td><td>it</td><td>is</td><td>!</td>
</tr><tr>
<td>spk2:</td><td> </td><td> </td><td> </td><td> </td><td>no</td><td>it</td><td>isn't</td><td>.</td><td> </td><td> </td><td> </td>
</tr>
</table>

The sensible way to display this is a flat sequence of tokens is to let spk1 finish his utterance and then move on to spk2. To do this we must follow this algorithm:
1. Scan all desired text layers defined by mappings (in this case, spk1, spk2)
2. Find the earliest span (token index) that has not been serialized yet, in case of a tie select the first layer by alphabetical name (spk1). If there are no more spans to serialize, you are done.
3. serialize all adjacent spans from the layer  selected in 2. (e.g. "This ... example.")
4. As soon as there is no more consecutive span, return to 2.

The loop in 4. causes the serialization of the following text:

This is an example. no it isn't. Yes it is!

To see the speaker switches, features #50 and #49 can be used to create line breaks and annotations:

<i>spk_name="Tim"</i> This is an example.
<br><i>spk_name="Mirko"</i> no it isn't.
<br><i>spk_name="Tim"</i> Yes it is!

**Comment by amir-zeldes** [comment]
The original part of this issue (for Falko and other non-dialogue corpora) is solved by HTMLVis. For dialogue, I think this is very specific to the scenario in the way that it's been annotated for BeMaTaC. This kind of visualization would be easy using HTMLVis if there is another layer giving complete utterances, i.e. if in the grid above, spk1's tokens are spanned by a single layer saying "this is an example", etc. 

Even in the case with token by token splitting and no utterance, it might be possible to use creative css, such as placing spk1's divs at an offset above line height and spk2 below. In any case, I'm not sure this kind of highly tailored algorithm needs to be realized to satisfy BeMaTaC's scenario - adding a full utterance span might be more cost effective in my opinion, and can be automated as well.
