### ISSUE TITLE
Order of annotations in KWIC should be configurable

### ISSUE THREAD

**Issue by thomaskrause** [korpling/ANNIS#28]
This is a request from Jena. It would make sense to make this configurable in the resolver. It could be done in mappings just like for the grid view.

However, since KWIC is available by default, there's usually no resolver entry for it. Maybe we should make it enterable in the resolver, with a possible mappings value specifying that KWIC should not be shown, in case we have corpora where we want to do that. Other suggestions where this could be configured are welcome.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-06-20T20:20:29Z
 * owner: amir-zeldes
 * assignee: annis
 * the launchpad url was https://bugs.launchpad.net/bugs/799924

**Comment by amir-zeldes** [comment]
Question @thomaskrause : since KWIC now inherits from grid can have a resolver entry, is this also solvable using the same mappings?

**Comment by thomaskrause** [comment]
Yes, this should be possible with the "annos" mapping (http://korpling.github.io/ANNIS/doc/classannis_1_1visualizers_1_1component_1_1grid_1_1_grid_visualizer.html). It is also possible to overwrite the default KWIC entry so I think we can close this issue.
