### ISSUE TITLE
New feature: WHiG corpus

### ISSUE THREAD

**Issue by thomaskrause** [korpling/ANNIS#29]
One subcorpus of FalkoEssayL2V2_O is/will be the WHiG corpus (What's Hard in German?). As part of the dissemination to other researchers and the funders AHRC and DFG, please include the option to select the WHiG corpus separate from the entire FalkoEssayL2V2_O. That way, researchers can research/compare data in the L1 corpus and WHiG corpus only.

Danke!

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2011-07-07T13:19:31Z
 * owner: m8r-q6o3pl
 * assignee: annis
 * the launchpad url was https://bugs.launchpad.net/bugs/806963

**Comment by amir-zeldes** [comment]
This is already the case.
