### ISSUE TITLE
Unicode char isn't escaped on import of new corpus (org.springframework.jdbc.BadSqlGrammarException)

### ISSUE THREAD

**Issue by sdruskat** [korpling/ANNIS#293]
On importing a corpus including the Unicode character "ḻ" (U+1E3B, LATIN SMALL LETTER L WITH LINE BELOW, http://unicode-search.net/unicode-namesearch.pl?term=LATIN+SMALL+LETTER+L+WITH+LINE+BELOW&.submit=Daten+absenden), _annis-admin.sh_ throws below JDBC BadSqlGrammarException.

Manually escaping the character in the _relANNIS_ source files (\ḻ) is a workaround.

A quick fix could be to catch the exception and give the user some useful information about why this might have happened.

Partial stack trace:
Exception in thread "main" org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [INSERT INTO example_queries (example_query, description, "type", nodes, used_ops, corpus_ref) VALUES (
'"buḻ'yun"', 'search for the word "buḻ'yun"', 'null', '1', '{}', '3'
)]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "yun"

**Comment by thomaskrause** [comment]
We upgraded to a new version of the PostgreSQL JDBC driver in the 3.5.0-preview5 release. Does this error still exists in the current version?
