### ISSUE TITLE
feature request - support Apache auth

### ISSUE THREAD

**Issue by ericmpi** [korpling/ANNIS#342]
There should be a possibility to disable the ANNIS built-in login/logout/whoami processing and let it use the "remote user" as provided by Apache instead. This would for example allow easy Shibboleth-wrapping of ANNIS instances:

> `<Location /ds/annis>`
>   SSLRequireSSL on
>   AuthType Shibboleth
>   AuthName "Login to search in corpora with ANNIS"
>   Require shibboleth  # use Shibboleth for this location
>   ShibRequireAll On
>   Satisfy All
>   ShibRequireSession On       # Off would make login optional
>   # ShibUseHeaders On # old-style envvar forward-to-webapp
>   Require valid-user # or user name1 name2 ...
> `</Location>`

If it would be possible to make the login button of ANNIS link to arbitrary URLs or even trigger javascript, the Apache config example above could be changed to "ShibRequireSession Off" and the user could press the login button in ANNIS at any point to switch from not logged in to logged in via Shibboleth or any other external login mechanism managed by Apache.

Note that ANNIS should display the remote user according to Apache to give the user feedback. At the moment, ANNIS would only display the user name or not-logged-in-status according to the built-in login system of ANNIS.

Also note that this means that the engine part of ANNIS will have to believe the GUI part who you are, because the GUI part will no longer have access to user passwords. That way, the GUI part itself cannot login with the user password to the engine part. This is perfectly okay for me because I can firewall direct access to the engine part and because the engine should not allow anything worse than leaking corpus content even if all checks are bypassed.

With the current version of ANNIS, I can already disable login processing in the engine part by configuration and tell Apache to process the logins. This leads to the cosmetic problem that ANNIS will still display the status and buttons for the built-in login processing nevertheless. Also, it leaves me unable to make actions depend on whether and as which user people are logged in, but that is okay for me for the time being.

**Comment by thomaskrause** [comment]
We are now using a similar scheme on our new ANNIS4 based web-service, since the ANNIS 4 web interface does not store its own users database anymore.

There is a Shibboleth-protected (with Apache Auth) web service that generates the required JWT token: <https://github.com/korpling/shibboleth-oauth2-forwarding>. We still have to document how to do this setup and provide binary files, but this will be much easier to implement than the previous attempts to generate internal temporary users.
