### ISSUE TITLE
Configure which text is used for the discourse visualization

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#35]
The discourse visualization currently uses the tokens from the first text it finds. It should be possible to use mappings to configure which text is taken as the basis for the discourse view. This should be determined using the namespace of the tokens in the desired text. If both the token namespace and the triggering edge namespace are configured, then only edges of the right namespaces in the right text are visualized. If the edge namespace is configured but no token namespace is found in mappings, the first text found to contain the right edge namespace should be visualized. If no text has the desired edge namespace, the first text found should be taken (this is the current behavior).

**Comment by thomaskrause** [comment]
The visualizer will now output all texts, which improves the situation (even if you can't configure which text to use).
