### ISSUE TITLE
Nodes, Edges und SecEdges in Konstituentenstruktur (tree) sind leer oder werden nicht angezeigt

### ISSUE THREAD

**Issue by Annotation-123** [korpling/ANNIS#367]
Obwohl sie abfragbar sind, werden die Label von Knote und Kanten nicht angezeigt und sekundäre Kanten werden nicht abgebildet.

Bei einer Suche nach den sekundären Kanten (z.B.) weden Start- und Endpunkt farblich markiert. Bei einer Suche nach einem bestimmten Knotentyp (z.B. np) wird die entsprechende Umrandung eingefärbt - die Beschriftung fehlt aber. 

Das Ganze war sowohl bei Bäumen, die mit Synpathy erstellt wurden, als auch bei solchen, die mit Atomic erstellt wurden, der Fall.

Außerdem habe ich versucht, PointingR über den arch_dependency-viewer anzeigen zu lassen, hier war auch Abfragbarkeit gegeben und es wurden auch der Start- und Endpunkt farblich markiert. Es fehlte aber der entsprechende Pfeil.

Muss vielleicht noch etwas installiert werden?

Der Fall bei:
annis 3.0.1 und 3.1.6
firefox und chrome

**Comment by Annotation-123** [comment]
Gibt es dazu mittlerweile eine Lösung? Habe jetzt auch nochmal den direkten RelANNIS-Export aus ATOMIC genutzt. DIe sekundären Kanten sind da, werden aber nicht angezeigt.

**Comment by thomaskrause** [comment]
Ich glaube wir brauchen zum debuggen ein Beispielkorpus (ein Satz z.B.) bei dem das Problem auftritt. Dann könnte ich näher in die Daten reinschauen und rausfinden warum der Visualizer die sekundären Kanten herausfiltert.

**Comment by thomaskrause** [comment]
Ok, anhand der Testdaten konnte ich das Problem nachvollziehen. Die sekundären Kanten waren als Pointing Relation modelliert, müssen aber auch Dominanz-Kanten sein um in der Visualisierung angezeigt zu werden. Um den Dominanzkanten den Typ "secedge" zuzuweisen muss man in Atomic die Pseudo-Annotation "t:secedge" an die Kante hinzufügen.

![atomic_secedge](https://cloud.githubusercontent.com/assets/2168104/5975922/01872a40-a888-11e4-9109-c25703226465.png)

Danach kann man mit 
```
node & node & #1 >secedge #2
```
danach suchen (also auch ">secedge" anstatt "->secedge") und die die Tiger-Visualisierung zur Anzeige nutzen
![annis_secedge](https://cloud.githubusercontent.com/assets/2168104/5975933/31b7a23a-a888-11e4-89cf-259a15781825.png)

**Comment by amir-zeldes** [comment]
OK, wenn ich das richtig verstehe, beantwortet das die Frage (tree ist für Dom-Kanten gedacht, d.h. PRs werden dan grundsätzlich nicht dargestellt.). Falls da noch Fragen sind, wie man das im Korpus modellieren könnte, sagt bitte Bescheid.
