### ISSUE TITLE
Init to update your Database ANNIS Kickstarter Fehler medlung Annis 3.2.0 und 3.2.2

### ISSUE THREAD

**Issue by Annotation-123** [korpling/ANNIS#386]
Ich kann ANNIS Kickstarter 3.2.0 und 3.2.2 (Windows 8, Mac 10.9.5) nicht öffnen, weil beim "Init to update your Database" eine Fehlermeldung kommt. 

--------------------------
Error in corpus: init database exception:
--------------------------
PreparedStatementCallback; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: FEHLER: Funktion array_remove(text[], unknown) existiert nicht
  Hinweis: Keine Funktion stimmt mit dem angegebenen Namen und den Argumenttypen überein. Sie müssen möglicherweise ausdrückliche Typumwandlungen hinzufügen.
  Position: 232

ANNIS 3.1.6 und 3.1.8 funktionieren.

**Comment by thomaskrause** [comment]
Welche PostgreSQL-Version wird denn benutzt?

**Comment by Annotation-123** [comment]
Falsche Version verwendet!
