### ISSUE TITLE
HTML visualization config parser error

### ISSUE THREAD

**Issue by dlukes** [korpling/ANNIS#404]
Hi,

I'm trying to devise a custom HTML visualization for a multi-layer dialogue corpus and I've noticed that the HTML visualization config parser throws an error when the triggering condition contains a digit (which is part of a namespace in my case, so perhaps the issue is restricted to namespaces?).

Here's my `vis.config` file:

```
spk0:ort        p       value
```

And here's the error:

![annis_htmlvis_parser_error](https://cloud.githubusercontent.com/assets/2734517/7453753/eca36bf0-f26c-11e4-921c-e2904e18219c.png)

Perhaps `spk0:ort` is not a valid namespace + annotation name combination in ANNIS (I thought restricting myself to strings which are also valid XML attribute names would be enough -- maybe it's not?), but in that case it's slightly confusing that the only place this leads to an error is in the HTML visualization module.

I can easily rename my namespaces for the time being, but it would be nice to solve this in a consistent way in the long run :)

I'm using the current release (ANNIS 3.2.3), by the way.

**Comment by thomaskrause** [comment]
Thank you for reporting this bug. I made a fix to make the parsing of the html visualizer and the normal AQL more consistent and the fix will be included in the next ANNIS release.

**Comment by dlukes** [comment]
Thanks!
