### ISSUE TITLE
HTML visualization -- escaping special chars

### ISSUE THREAD

**Issue by dlukes** [korpling/ANNIS#405]
Is there a way to force the HTML visualizer to escape special characters (angle brackets, ampersands etc.) inside annotations? As things stand, if an annotation consists e.g. of the string `<SM ha ha ha>`, it is outputted verbatim and therefore interpreted as an HTML tag by the browser.

There's a `switch` statement in `annis.visualizers.htmlvis.SpanHTMLOutputter`, in the method `outputHTML`, which should escape the value of the matched annotation when `type` is `ESCAPED_VALUE`, but I can't figure out what affects this attribute or how to set it to `ESCAPED_VALUE` (apologies, I read Java like a five-year-old at best).

**Comment by PatrickJazzMea** [comment]
Java is escaped using a back slash (\) before the character that you want to escape. Oracle has all the information that you could possible need. Apache commons has the StringEscapeUtils available which should be useful.

**Comment by dlukes** [comment]
Thanks, but I'm not sure backslash escapes will help me here, as this is a matter of generating entities (`&lt;` etc.) instead of characters which HTML interprets as markup (`<` etc.). It's not that I can't cobble together a quick and dirty fix either (see above), I was rather wondering whether there is a standard userland option to trigger this behavior.

**Comment by PatrickJazzMea** [comment]
I don't think there is a standard user land option to trigger this behavior that comes with the java sdk if that's what you are asking.

**Comment by dlukes** [comment]
I didn't mean Java in general but this application (ANNIS) and its config files in particular :)

**Comment by PatrickJazzMea** [comment]
Aaah gotcha, I'll have to look into it further

**Comment by thomaskrause** [comment]
Hi,

you can enforce escaping of the annotation values by specifying the output type. In general the rules have the form
```
condition  output_element  output_type
```
e.g.
```
title     b                            value
```
will output a "<b>annovalue</b>" whenever a title annotation is seen.
In you case you should use "escaped_value" instead of "value".
```
title     b                            escaped_value
```
This is unfortunately not documented in the  HTML visualization guide yet, I will ask @amir-zeldes to do that (there is  currently only a feature request #238 which describes this behavior).

**Comment by dlukes** [comment]
Awesome! I figured there would be an easy solution, thank you very much :)

**Comment by amir-zeldes** [comment]
OK, the guide has been updated!
