### ISSUE TITLE
Browse documents feature

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#43]
There should be a button called "browse corpus" (or something like that), which corresponds to a query finding the beginning of each document in the corpus. The query should be built using the current left context setting, so that the search finds the "left context+1" token. This way, we see a maximally long hit: the searched token, <context left> tokens to the left and <context right> tokens to the right. Because each match is from a different document, there are no repetitions among the results.

If the corpus has e.g. 1971 documents, then we see 1971 search results. This way the user can get an idea of the texts in the corpus, and if the discourse view is used, they can also read each document. For browsing syntax trees, the administrator can set the tree view to be automatically displayed (fulfills feature request from Detmar Meurers).

**Comment by thomaskrause** [comment]
There is now a general document browser, which lists the documents and allows to show a visualizer like the full-text visualizer for the whole document. In case you want to have an impression what kind of annotations there are, a simple `tok` query should be sufficient, since the document itself is not that important in this case.

**Comment by amir-zeldes** [comment]
Thanks - just a note to say, most beginner users aren't aware of the usefulness (or even possibility) of the "tok" query, so having some beginner friendly UI elements may be helpful even though this possibility already exists.

**Comment by thomaskrause** [comment]
I just checked and the "tok" query is not explicitly mentioned in the tutorial as a way to explore the corpus results and annotations. You are right, we should make it easy to guess what do to next after opening the interface. Currently the top-left hint is prompting to insert a query. We could be more specific here like actually mentioning the tok example query. Also the hint to the tutorial is only in  the status field below. I will try to both add the tok query to the user guide and also thinking about better hints in both the status field and the query box.

**Comment by amir-zeldes** [comment]
tok is great for power users, but for beginners I often find showing a word search is less intimidating (like, a mid-frequency term that has a few hits, but not the whole corpus with a 1 word offset across KWIC results...). 

I'd still like to see corpus sizes in the corpus selection though, since that often is a quick indicator of whether you are looking at the corpus you think you're looking at / which ones are relevant.
