### ISSUE TITLE
Regex search ignores escape on forward slashes

### ISSUE THREAD

**Issue by fpetran** [korpling/ANNIS#498]
A forward slash inside a regex is always interpreted as terminating the regex, regardless if it's escaped or not.

Reproducible: always
Steps to reproduce:
1. enter search `tok = /.*\/.*/`
Expected result: find toks containing "/"
Actual result: error `line 1:9 extraneous input '/' expecting {<EOF>, '&', '|'}`

Tested with: 3.3.6, 3.4.0-rc4

**Comment by thomaskrause** [comment]
Unfortunately the `\/`escaping is not implemented yet in our grammar. You can use `\x2F`as a workaround to search for slashes, e.g.
```
tok=/a.*\x2F.*/
```
https://korpling.org/annis3/?id=1f10998f-25bf-4499-a444-8760026b21cb

I will check the our parser to see if there is an easy way of implementing this.

**Comment by thomaskrause** [comment]
Our current grammar parses this when using graphANNIS as a back-end. The underlying regular expression engine however does not support this specific escape sequence:
https://docs.rs/regex/1.3.4/regex/#escape-sequences

As there is a workaround and we can't easily extend the regex engine I will close this issue.
