### ISSUE TITLE
Resolver doesn't show annotations on tokens in docs with > 1 tokenizations and no spans governing the tokens

### ISSUE THREAD

**Issue by sdruskat** [korpling/ANNIS#527]
What is the used ANNIS version?
**3.1.0-SNAPSHOT**

What browser and operating system did you use?
**Ubuntu 14.04, Firefox**

What steps will reproduce the problem?
**1. Create a corpus document with two tokenizations.
2. Let tokens from one of them not be governed by any spans
3. Export to ANNIS and display**

What is the expected result?
**ANNIS shows all annotations on tokens**

What happens instead?
**ANNIS doesn't show the annotations**

Please provide any additional information below. Also please add a screenshot if possible.
**Bug can be circumvented by adding one span per token, or adding all tokens to one span.**

**Comment by thomaskrause** [comment]
Seems to be fixed in newer versions. I tried both with artificial tokenization and with parallel separate texts and in both cases the token annotations where shown either in the grid or in the KWIC view.
