### ISSUE TITLE
Implement templating for grid

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#530]
Currently the templating mechanism only works for the HTML visualizer. However, for many applications it would be useful to have templates also in the grid view: for example, we could have dictionary linkup from grid results, whereas currently we would have to open an HTML visualizer to do this.

Since the only configurable location in the grid implementation is the mappings column in resolver_vis_map, this is probably the least invasive point to implement this feature. We could use the following syntax, addable as an additional semi-colon separated mapping:
- The name of the mapping property is `templates`, and it can contain multiple template instructions. 
- The value consists of an instruction and a template
  - The instruction can be an annotation name, or a combination of annotation name and value which looks like an AQL query (i.e. we use either `lemma` or `lemma="house"`)
  - The value is a template following the HTML vis template scheme, meaning a constant string, optionally containing the reserved sequence `%%value%%` to represent the value of the annotation. The value sequence can be used multiple times, and there is no need for an `%%anno%%` option, since the instruction is specific to an annotation name
  - As a separator between instruction and template we can use an arrow like this `==>`
  - As a separator between multiple templates, we can use double pipes: `||`

Some examples

```
# Single template, triggered by anno name only:
templates:lemma==><a href="http://mydictionary.com/%%value%">%%value%%</a>
# Two templates, triggered by anno name only, the second has a constant template with no %%value%%:
templates:pos==><a href="http://myposlookup.com/%%value%%">%%value</a>||entity==><b>%%value%%</b>
# Template based on anno+value combination, rendered as font awesome icon:
templates:entity="person"==><i class="fa fa-male">&nbsp;</i>
```

**Comment by amir-zeldes** [comment]
BTW another neat application of this is that it's easy to give specific annotation rows individual colors, using a mapping that just puts a styled span around specific annotation rows.

**Comment by thomaskrause** [comment]
Closed by the previous pull request. Please re-open if you disagree.

**Comment by amir-zeldes** [comment]
Agreed, templates work great!
