### ISSUE TITLE
arabic in raw_text

### ISSUE THREAD

**Issue by TFeige** [korpling/ANNIS#538]
What is the used ANNIS version?

Version: 3.4.4 (rev. b53ef2e654, built 2016-05-13 17:08:12)
What browser and operating system did you use?
Ubuntu 16.04 / Firefox 49.0.2

What steps will reproduce the problem?
1. Arabic text with bidi-characters

What is the expected result?
correct order of characters. See screenshot:
![arabic-correct](https://cloud.githubusercontent.com/assets/19265315/19896034/43a67d80-a053-11e6-9dd2-5567259fb9d2.png)

What happens instead?
Wrong order:
![arabic-direction](https://cloud.githubusercontent.com/assets/19265315/19896062/536ba740-a053-11e6-99f5-8ef3b06ae1f6.png)
 

Please provide any additional information below. Also please add a screenshot if possible.

Assigning "direction: right;" to the element solves this problem. 
Together with "text-align: right;" Arabic will be displayed in the expected way.

Setting the alignment to the right side makes Arabic text more readable, especially if it is set to block text.

**Comment by thomaskrause** [comment]
The raw text visualizer did not explicitly handle RTL text as e.g. the Grid and KWIC visualizer does. The browsers seem to default to RTL when there is only arabic script in the text but they go back to left to right when there is any "non-RTL" character in the text. I implemented explicit handling of the case in the visualizer itself, thus if there is any RTL character RTL is favored.

**Comment by thomaskrause** [comment]
> Setting the alignment to the right side makes Arabic text more readable, especially if it is set to block text.
I would make an extra issue for that since depending of the context of where the visualizer is used (result view, document view) there might be issues with the overall layout.
