### ISSUE TITLE
Refresh query builder when AQL was changed in text field

### ISSUE THREAD

**Issue by CarolinOdebrecht** [korpling/ANNIS#544]
What is the used ANNIS version?
annis3-snapshot

What browser and operating system did you use?
firefox / windows
Refreshing: All changes in the query builder are immediately refreshed in the query window, but not the other way around. This would be useful, when using both, the query builder and the query window.

**Comment by thomaskrause** [comment]
For this we would need to add some more complex REST APIs calls to actually parse the query and add a complete new mapping for the query (tiger) builder, which is quite costly to implement. I would argue to make it easier to build better query builders as separate projects and not include this into the existing ANNIS interface.
