### ISSUE TITLE
Multiple search tabs

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#55]
It would be nice to have multiple search result windows open in separate tabs. To do this, we could have two search buttons (or a search button with two halves somehow, or a button with a drop down menu like the history button with a drop down menu): 

"search" and "search in new tab"

The "search" button executes the search in the active results tab, or in a new tab if no result tab is selected.

**Comment by thomaskrause** [comment]
There was an experimental implementation doing this, but it made the query execution logic much more complex and was also confusing for some users.
