### ISSUE TITLE
Problem with "," in text names

### ISSUE THREAD

**Issue by fab-bar** [korpling/ANNIS#572]
I have encoutered a problem with using a comma in text names:
In the SaltAnnotateExtractor the ids of the matched nodes are joined using "," and added as feature "matchedids" to the graph:
https://github.com/korpling/ANNIS/blob/510fbafaf4ced90d231b685e07fb5a73c4956aaa/annis-service/src/main/java/annis/sqlgen/SaltAnnotateExtractor.java#L359

This is in exemplary "matchedids"-feature for a text that contains a comma:

`salt:/ReN_2017-09-05/Brem._StR_1303**,**08#sSpan491,salt:/ReN_2017-09-05/Brem._StR_1303**,**08#sTok5436_virtualSpan`

As the comma in the text name is not escaped, splitting the string at each "," leads to false ids.
This breaks the CSVMultiTokExporter.
I have changed it so that getting the matched nodes does not depend on the "matchedids" feature
(#571) which fixes the problem for the exporter.

But I still wanted to report this just in case this breaks anything else.

**Comment by thomaskrause** [comment]
Thank you for the fix, I merged pull request #571  and this will be part of the next release.
