### ISSUE TITLE
GridExporter fails for texts with "," in name

### ISSUE THREAD

**Issue by fab-bar** [korpling/ANNIS#576]
The problem described in #572 also breaks the GridExporter (Version: 3.5.0-preview6) .

You can see this with the results from https://annis.corpora.uni-hamburg.de/gui/?id=f2f54ac6-f16c-4b1c-9b5f-beb082161fc8 (Currently with Version 3.5.0-preview3).

**Comment by thomaskrause** [comment]
Closed by #577
