### ISSUE TITLE
Include *all* documentation in the /doc folder

### ISSUE THREAD

**Issue by sdruskat** [korpling/ANNIS#578]
## What is the used ANNIS version?

`development`

## What browser and operating system did you use?

n/a

## What steps will reproduce the problem?
1. Open the `/doc` folder
2. Look around for the User Guide sources
3. Find nothing ;)

## What is the expected result?

*All* documentation should be included and open sourced in the `/doc` folder, where everyone can help contributing to it, so to better keep it up-to-date.

## What happens instead?

n/a

## Please provide any additional information below. Also please add a screenshot if possible.

If the User Guide is still in a Word/OO/LO file, we can transform it to, e.g., Markdown with pandoc (happy to do it if I can get the original file) and include it in the `/doc` sources. Additionally this would be good to have for the other guides as well (HTML Viz, Multiple Segmentation).

**Comment by sdruskat** [comment]
@amir-zeldes My email archive tells me that you might have the master document for the User Guide? Care to share? I'm happy to convert to TeX/Markdown to make editable by the community.

**Comment by amir-zeldes** [comment]
Hi @sdruskat , sure, I can send them to you via e-mail, they're just Word files. If you have the time to convert them that would be great!

**Comment by thomaskrause** [comment]
Oh, this seems to be fixed by the latest releases that include a mdbook based documentation, including the content of the user guide.
