### ISSUE TITLE
Handling of PDF ExtData: deduplication + "master PDF"

### ISSUE THREAD

**Issue by sdruskat** [korpling/ANNIS#580]
These are questions rather than bug reports / feature requests (although may become the latter).

1. Say a fieldwork-generated corpus has several documents sharing the same ExtData (e.g., a PDF with a storyboard from the elicitation process that has been used for several informants). The relevant PDF pages should be displayed in a `pdf` visualization. At the moment, the respective PDF would have to be uploaded multiple times, i.e., for each document for which the same storyboard has been used. **Should we look into deduplication for the sake of server space?**

2. Alternatively, one could also imagine offering an option to use one single "master PDF" (where this makes sense (where would it where it doesn't break corpus/document semantics, etc.?)) which contains all the partial documents, and simply linking to that (e.g., a single PDF in the `{ANNIS sources}/ExtData/` dir. **Is this a viable option?**

Happy to hear everyone's opinions and work on the implementation.

**Comment by thomaskrause** [comment]
Since the current implementation downloads the complete PDF and then jumps to the correct page via the annotations, I think splitting the PDF is a better option.
