### ISSUE TITLE
Loading iframe based visualizers fails if instance URL ends with slash

### ISSUE THREAD

**Issue by thomaskrause** [korpling/ANNIS#581]
What is the used ANNIS version?
3.5.0-preview6

What steps will reproduce the problem?
1. Open https://korpling.org/annis3/ddd/#_q=dG9r&_c=cGNjMg&cl=5&cr=5&s=0&l=10
2. Click on dependency visualization

What is the expected result?
iframe is loaded with visualization

What happens instead?
new embedded ANNIS instance is loaded

**Comment by amir-zeldes** [comment]
I can confirm that this is still affecting 4.0.0-beta.3-SNAPSHOT (rev. be0b09758e) - the rstVis is now fixed (thanks!), so if this is fixed we should be able to deploy graphANNIS for production testing at Georgetown.
