### ISSUE TITLE
_o_ operator ignores reflexivity constraint

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#590]
What is the used ANNIS version?

3.5.0-preview5 (rev. 20ffc21416, built 2017-10-09 11:48:10)

What browser and operating system did you use?

Chrome, backend on RHEL6, front end on Win10-64

What steps will reproduce the problem?
1. Select GUM (V4)
2. run AQL `entity _o_ entity _o_ entity _o_ entity`
3. results return 71K+ hits, due to ignoring reflexivity constraint (most results have just two spans, which each count as two of `#1,#2,#3,#4`)
4. note that the same query with `_i_` works as expected: `entity _i_ entity _i_ entity _i_ entity` (143 hits)

What is the expected result?

Something closer to 143 hits (entities usually properly nest, so maybe just a couple more)

What happens instead?

Huge cross-product.

Please provide any additional information below. Also please add a screenshot if possible.

**Comment by amir-zeldes** [comment]
Depending on the timeline for releasing ANNIS 4 it could be fine to leave this alone for now, but I don't think it's ambiguous... For me at least it seems like a bug, when searching for 4 overlapping entity annotations, that I could get a result with only two unique nodes. 

And it's also internally inconsistent - if this were really the intended semantics of AQL, then the same kind of result would be expected for 4 nodes joined by `_i_`: any two spans with identical coverage would be returned for any number of elements in a multiple inclusion query, but that doesn't happen currently (which I think is correct!). I wouldn't be worried about altering current query results since this is definitely the wrong result set in my view, but I doubt anyone is running such queries, since they would notice the huge result set pretty quickly.

Anyway we can close this if ANNIS 4 is in the somewhat immediate horizon and already addresses this, then the fix is just switching to ANNIS 4 :)

**Comment by thomaskrause** [comment]
> And it's also internally inconsistent - if this were really the intended semantics of AQL, then the same kind of result would be expected for 4 nodes joined by `_i_`: any two spans with identical coverage would be returned for any number of elements in a multiple inclusion query, but that doesn't happen currently (which I think is correct!). 
It is actually consistent, its just that for 4 elements with `_i_` its very unlikely, e.g. if you search for 
`entity _i_ entity _i_ entity `
you also get this match which shows the same behaviour:
https://korpling.org/annis3/?id=40e5611c-b46a-41e7-ac8b-3fb726e25de4

Also, what should we do when the operators are mixed like in 
`entity _o_ entity _i_ entity`?

Currently, reflexivity is implemented as a local property of the operator. There is indeed an additional constraint, that the result set is unique, but this is again defined on the whole result vector where each element is defined by the position in the query.
I think what you have in mind is a constraint on the result definition, that at the same matched node/annotation can't be in more than one position of the single result. But this really might have consequences for other queries..

**Comment by amir-zeldes** [comment]
Thanks for finding that, that example is an annotation error! But the way it is annotated, I still consider this result an error. If a user is looking for three entity annotations, they are not expecting to get back a hit with only two distinct annotations. If they want to impose a second constraint on one of two annotations, they would use that match's node number, no?

What I want (and in fact I thought this was the case) is that two declared, numberable criteria (`#1, #2 ...`) can never refer to the same annotation (though they can refer to two distinct annotations of the same node). If they refer to the same annotation, then they are both `#1` etc., whereas in `entity _o_ entity` it is clear that these criteria receive different indices. In the special case of exactly two criteria, it seems that this is in fact what happens.

Since this seems not to be the case right now for more than two criteria, I agree that enforcing this mutual exclusiveness may change some result sets, but unless you have a strong argument why this is not the expected behavior from a user perspective, I'd say the result sets that would be changed were previously incorrect (or at least counter-intuitive for users).

**Comment by thomaskrause** [comment]
Fixed in 4.0.0-beta.1
