### ISSUE TITLE
Find relations with no edge label

### ISSUE THREAD

**Issue by otichy** [korpling/ANNIS#604]
Hi!

I am working with a PCEEC corpus that has edge labels, so I can find e.g. all NPs that are subjects:
cat=‎"NP‎" & node 
& #2 >[func=‎"SBJ‎"] #1

But not all NPs have an edge with a label, so that [func=‎"SBJ‎"] plus [func!=‎"SBJ‎"] do not add up to the total number of NPS. I would like to find all unlabeled nodes. This not surprisingly does not work:

cat=‎"NP‎" & node
& #2 >[func=‎"‎"] #1

Any way ANNIS could do this?

What is the used ANNIS version?
Version: 3.6.0 (rev. 885a2c8a40, built 2019-02-12 15:12:48)

What browser and operating system did you use?
Chrome Version 72.0.3626.121 (Official Build) (64-bit)
Windows 10 64bit Version 1803

Best

Ondrej

**Comment by thomaskrause** [comment]
I'm very sorry that I have overlooked this issue for such a long time.

Currently, ANNIS does not support searching for elements that do not exist (see #194 and #195 for suggestions how to implement different kind of negations).
It was difficult to implement using the SQL-based approach and the way edges where represented (we are always searching for nodes and edges are just additional constraints, not actually part of the result).

In this case, if there is an edge but this edge has an empty label it should be possible to search for the empty label. This means that probably there is no edge in the annotation graph or that the edge/label was lost somewhere during the conversion from a different format.

**Comment by amir-zeldes** [comment]
Just to clarify: it is possible to alter the corpus so that there is either an empty label, or perhaps somewhat more transparently, to annotate all 'no label' edges with some value, such as `_`, and then search for that value - but this decision would be up to the corpus designer converting the original data to ANNIS. It's not something you could do on the fly in the interface.

**Comment by otichy** [comment]
OK, thanks for looking into this. And thanks for pointing me to #195 that helped with other issues I've had.
