### ISSUE TITLE
Typo and outdated info in PostgreSQL tips

### ISSUE THREAD

**Issue by dlukes** [korpling/ANNIS#607]
The `advanced-postgresql.md` file in the docs has a typo in one of the config options (`default_statistcs_target`), and another one (`checkpoint_segments`) has been [removed in more recent versions of PostgreSQL, starting with 9.5](https://www.postgresql.org/docs/9.5/release-9-5.html). Cf. suggested changes in my fork:

https://github.com/korpling/ANNIS/compare/develop...dlukes:develop

**Comment by thomaskrause** [comment]
Thanks for the update, I added this commit to the annis3/develop branch in case we have a future ANNIS 3 bugfix release.
