### ISSUE TITLE
rstdoc broken in 4.0.0-beta.2

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#615]
@thomaskrause , I'm testing ANNIS 4.0.0-beta.2 on GUM now and two problems appear in rstdoc in the front-end:

1. Leaf node display an ID like `structure883` instead of their EDU number (1, 2, 3 etc.)
2. Tokens are randomly scrambled within leaf node text

See both errors in this screenshot:

![image](https://user-images.githubusercontent.com/2188635/62779549-836cbd80-ba81-11e9-86e0-98a1ecc46409.png)

**Comment by thomaskrause** [comment]
The issue with using the node name as ID instead of the sentence index was a "intended behavior" introduced with the latest changes on the RST visualizer to support signals. I updated it to use the sentence ID again, but only display a single number if left and right are the same.
