### ISSUE TITLE
Segmentation set for context definition does not work

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#624]
The segmentation set in corpus.properties for `default-context-segmentation` is ignored in the interface, which continues to show context size based on +/- 5 tokens. The same thing happens if context is set in the Options tab ('show context in') - tokens are still used to determine context size. The corpus.properties setting `default-base-text-segmentation` DOES work though - it's only the context size that's ignored.

Version: 4.0.0-beta.3-SNAPSHOT (rev. 09b23e6bc7, built 2019-10-03 10:49:59)

To reproduce, use any Scriptorium corpus from here:

https://github.com/CopticScriptorium/corpora

Example properties file with segmentation=norm_group:

https://github.com/CopticScriptorium/corpora/blob/master/AP/apophthegmata.patrum_ANNIS/ExtData/corpus.properties#L6

**Comment by amir-zeldes** [comment]
@thomaskrause do you know if there is any change to the syntax or configuration that I missed, or changes to the Order Relation manipulator maybe? The corpora all have data from the ANNIS3 era, so they were just imported under the assumption that everything is the same. I think segmentations must be somewhat intact because base text works fine.

**Comment by thomaskrause** [comment]
This should absolutely work as you describe it and its an oversight its not in the beta-release yet. I currently have a working solution, but with some performance issues I need to resolve before merging it into `develop`.
