### ISSUE TITLE
Visualization of parallel corpora not working in ANNIS4

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#627]
When searching in parallel corpora with a query containing alignment, KWIC / grid show the data from the two languages next to each other instead of under each other, as if text from both languages is coming from a single text (e.g. example query in SMULTRON_Banana)

The discourse visualization, which used to be able to show parallel corpora in multiple frames and used the colorful underscores to indicate alignment edges, now completely crashes when opened, saying "Could not find any texts for the XYZ namespace":

![image](https://user-images.githubusercontent.com/2188635/68773555-c77bdb00-05f9-11ea-970f-e7a95748bef5.png)

**Comment by thomaskrause** [comment]
This should be fixed in the latest develop branch. Please reopen if the error still occurs.

**Comment by amir-zeldes** [comment]
Will test, thanks!
