### ISSUE TITLE
Share button creates URL which loads no base text on corpora with segmentations

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#630]
For the Coptic query `lemma="ⲏⲓ"` in some Coptic corpora, copy-pasting the browser URL creates a correct link, which can be used to reproduce the query:

https://corpling.uis.georgetown.edu/annis/scriptorium#_q=bGVtbWE9IuKyj-KykyI&ql=aql&_c=YXBvcGh0aGVnbWF0YS5wYXRydW0sY29wdGljLnRyZWViYW5r&cl=5&cr=5&s=0&l=10&_bt=bm9ybV9ncm91cA

Using the share button, the following incorrect link with segmentation specification is generated:

https://corpling.uis.georgetown.edu/annis/scriptorium#_q=bGVtbWE9IuKyj-KykyI&ql=aql&_c=YXBvcGh0aGVnbWF0YS5wYXRydW0sY29wdGljLnRyZWViYW5r&cl=5&cr=5&s=0&l=10&_seg=WW0wNWVXSldPVzVqYlRreFkwRQ

Note that the base text URL parameter is not set, but seg is specified. This results in an empty KWIC vis:

![image](https://user-images.githubusercontent.com/2188635/68963611-4f521880-07a5-11ea-8437-78f8fc2014bc.png)

This can be reproduced using any Coptic corpus (e.g. apophthegmata.patrum)

**Comment by thomaskrause** [comment]
This should have been fixed with 1ef1a348460fac0489c78b461ec9e320670f6ea6
