### ISSUE TITLE
Search for absence of an edge?

### ISSUE THREAD

**Issue by nschneid** [korpling/ANNIS#653]
I would like to be able to search for a node in a tree that lacks any dependents of a certain type, e.g.

    upos=‎"ADP‎" ->ud tok & #1 !->ud[deprel=‎"cop‎"] tok

The `!->` notation is not supported syntax. Is there another way to accomplish this?

**Comment by thomaskrause** [comment]
Hi, this is currently not possible if the corpus does not have other types of edges that explicitly mark a "non-dep" relationship (which could be quite an explosion in edges). We are tracking the issue of searching for non-existing elements in #195 . Which corpus are you using? @amir-zeldes Do you have an idea how to circumvent searching for non-existing items in this particular query?

**Comment by nschneid** [comment]
It's an in-house corpus but basically the Universal Dependencies version of the English Web Treebank (UD_English-EWT). Yes, looks like #195 is the same issue. Thanks

**Comment by amir-zeldes** [comment]
Thanks @thomaskrause - this is an issue that comes up again and again, but unfortunately without proper negative search there is no direct way to do it. The alternatives without changes to ANNIS are:

  * Add a node annotation that has all child functions of each token, which can then be targeted with a negative regex (child_funcs!=/.*cop.*/)
  * Export results for two queries, one actually looking for cop, one without restrictions, then take the complementary set of IDs to the intersection.

If subsetting ('search within results') were supported in ANNIS, the second approach could almost be applied in the UI by offering some kind of 'give me the complementary set' after a subquery, but that's not currently possible either...

The concrete suggestions in #195 are probably not relevant now that graphANNIS is not SQL based (so not 'where not exists' possibilities), but if there were a native way to get negation, or even subqueries/complements, in graphANNIS, that would be great of course!

**Comment by thomaskrause** [comment]
This has been implemented in ANNIS 4.5.0 by combining negated operators (`!->ud`) and optional node definitions for non-existing nodes (`tok`).See <http://korpling.github.io/ANNIS/4.5/user-guide/aql/negation.html> for a description.
