### ISSUE TITLE
Random result order fails on disjunction

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#654]
If a query contains a disjunction, random result order fails.

**To Reproduce**

Search GUM for `pos=‎"RB‎" _=_ claws5=‎"ORD‎" | pos=‎"VV‎"`, choose random order. No result is displayed but results bar says `Result for: unknown error: com.sun.jersey.api.client.UniformIn`

Using: Version: 3.5.0-preview5 (rev. 20ffc21416, built 2017-10-09 11:48:10)

**Comment by thomaskrause** [comment]
I tested it with 3.6.0 and the bug still exists

**Comment by thomaskrause** [comment]
This has been fixed in ANNIS 4.1.x
