### ISSUE TITLE
Search results not showing second half of results

### ISSUE THREAD

**Issue by lehmannx** [korpling/ANNIS#655]
**Describe the bug**
The last (about halfway through) search results are not shown. From 750 results (76 pages), the pages from 35 above display "No matches found" instead of the results. With only 200 results, the same happens at about the middle of all results.

**To Reproduce**

1. Search for something
2. Go to last result page
3. See "No matches found"

**Screenshots**

<img width="1440" alt="Screenshot 2020-03-17 at 08 18 04" src="https://user-images.githubusercontent.com/25769276/76831579-e00a3500-6827-11ea-8aac-0e858abd7b7b.png">

**Desktop (please complete the following information):**
 - Operating System: [e.g. macOS Catalina]
 - Safari
 - Java 12 .0.2 OpenJDK Runtime Environment (build 12.0.2+10) OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
 - ANNIS Version 4.0.0 beta3

**Comment by thomaskrause** [comment]
I could not reproduce with the LYC-* corpora. Did you select multiple corpora and if yes, which ones?

**Comment by lehmannx** [comment]
I’m actually not sure if it also happened without selecting multiple corpora. When I checked right now with just one corpus, it didn’t occur. But with multiple corpora (does not matter which ones), it happens both with Firefox and Safari. My search string was just: ref=/.*/ this time.

**Comment by thomaskrause** [comment]
I can't reproduce it with the beta-release from yesterday (https://github.com/korpling/ANNIS/releases/tag/annis-4.0.0-beta.4). Can you check if it also solved on your end?

**Comment by lehmannx** [comment]
The Beta-Release is awesome. Everything works now just fine. 
Thanks you!
