### ISSUE TITLE
Kickstarter does not terminate "starting annis ..." with Java 11 (openjdk)

### ISSUE THREAD

**Issue by MartinKl** [korpling/ANNIS#679]
**Describe the bug**
Not sure this is a bug report or a feature request: When starting ANNIS kickstarter (both 3.6.x and 4.0) the stage "Starting ANNIS ..." does not terminate when using java 11. Switching to java 8 solves the issue.

**To Reproduce**

1. Set system lib to openjdk's java 11
2. Run AnnisKickstarter.sh
3. wait

**Expected behavior**
AnnisKickstarter should complete starting ANNIS for all java versions >= 8.

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 20.04
 - Java Version: openjdk 11 vs. openjdk 8
 - ANNIS Version: Kickstarter 3.6.0 and 4.0.0-beta.4

**Comment by thomaskrause** [comment]
In ANNIS4 beta 6 the startup routine has been enhanced. I tested it under Ubuntu 21.04 and OpenJDK the Kickstarter (now "desktop JAR" finishes as expected. Please re-open if this is still happening for you in ANNIS4.
