### ISSUE TITLE
is:issue is:open ANNIS 4 crashes on Kubuntu 21.04

### ISSUE THREAD

**Issue by novacellus** [korpling/ANNIS#702]
**Describe the bug**
ANNIS 4 fails to start on Kubuntu 20.10. It appears to be caused by the java.awt.Desktop.browse method which doesn't seem to be well supported in the KDE.

**To Reproduce**

`java -jar annis-4.0.0-beta.6-desktop.jar`

**Expected behavior**

The url can be open by the user, but the bug results in program crash.

**Screenshots**

![obraz](https://user-images.githubusercontent.com/7395279/127776976-07d3860c-da6c-479b-89d2-a16857c32e16.png)

**Desktop (please complete the following information):**
 - Operating System: Kubuntu 21.04, KDE Plasma Version: 5.21.4, Qt Version: 5.15.2
Kernel Version: 5.11.0-25-generic, Graphics Platform: X11
 - Java Version: tested with both openjdk version "1.8.0_292" and openjdk version "11.0.11" 2021-04-20
 - ANNIS Version: annis-4.0.0-beta.6-desktop.jar

**Comment by thomaskrause** [comment]
Thanks for the bug report, there is some code to handle exceptions and prompt the user to manually open the site in  https://github.com/korpling/ANNIS/blob/a1c04cc06b2c373ca5c34e002f2ee2654869bc1a/src/main/java/org/corpus_tools/annis/gui/ServiceStarterDesktop.java#L231 but it seems the `UnsupportedOperationException` was missed. I will also check if there is a workaround for KDE systems to actually automatically open the browser.
