### ISSUE TITLE
Embedded REST service should log why it fails to start (v4)

### ISSUE THREAD

**Issue by dlukes** [korpling/ANNIS#761]
When using the embedded REST service, I can see its own log messages interweaved in ANNIS's main log, viewed via `journalctl`. However, when the REST service crashes for some reason, the error which says what went wrong is not shown, e.g. this:

```
Error: Custom { kind: Other, error: "Could not initialize graphANNIS service: could not lock corpus directory data/\n\nCaused by:\n    Permission denied (os error 13)" }
```

I assume this is because this doesn't go through the logging interface, it just gets printed to STDERR?

This makes it quite hard to debug REST service startup issues. It's one of the reasons I ended up setting up a separate systemd service for the REST service, because these errors do show up there. Whereas with the embedded REST service, I guess they're swallowed up by the parent Java process.

**Comment by thomaskrause** [comment]
This is strange, the current code should in theory output the data in the same manner as the other log messages, using the configured Logger

```java
tReaderErr = new Thread(() -> {
              while (!this.abortThread.get() && backgroundProcess.isAlive()) {
                String line;
                try {
                  line = errorStream.readLine();
                  if (line != null) {
                    log.error(line);
                  }
                } catch (IOException ex) {
                  if (!this.abortThread.get()) {
                    log.error("Could not read service error output", ex);
                  }
                  break;
                }
                Thread.yield();
              }
            });
```

I investigate if I can reproduce this and why it fails to properly show in the journalctl output.
