### ISSUE TITLE
Working directory is overridden to JAR parent dir (v4)

### ISSUE THREAD

**Issue by dlukes** [korpling/ANNIS#762]
**Describe the bug**
[The docs](http://korpling.github.io/ANNIS/4.6/user-guide/configuration/index.html) claim that:

> ANNIS uses the Spring Boot configuration system and thus it will search for a Java Properties based configuration file named application.properties in the current working directory or a config sub-directory of the working directory.

But in practice, I've observed that the configuration file is discovered relative to the JAR location. Since this also affects any relative paths defined in the REST service's `service.toml` (`graphannis`, `sqlite`), I guess this is because the JAR actually overrides the working directory at some point.

**To Reproduce**
Start ANNIS with a systemd service file where the working directory and JAR parent directory differ, e.g.:

```service
WorkingDirectory=/home/annis
ExecStart=/home/annis/bin/annis-4.6.6-server.jar
```

And place the config file at either `/home/annis/application.properties` or `/home/annis/config/application.properties`. ANNIS won't find it, instead looking for `/home/annis/bin/application.properties` or `/home/annis/bin/config/application.properties`.

**Comment by thomaskrause** [comment]
This seems to be a specific behavior when the JAR file is treated as executable file (<https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html>). In this case the working directory is the one containing the JAR file. In case you start ANNIS with `java -jar /path/to/annis-server.jar`, the working directory is kept.
I will update the documentation to mention this difference.
