### ISSUE TITLE
Document running under a URL prefix (context path) in v4

### ISSUE THREAD

**Issue by dlukes** [korpling/ANNIS#764]
In v3, this was more clearly out of the scope of the documentation, as the deployment of the WAR file was a separate thing that users could look up guides for. In v4, the WAR deployment step has gone away, which is very convenient, I remember having troubles with it on occasion, but it also makes it less clear where to search for information on how to run ANNIS under a URL prefix if not provided directly in the ANNIS docs.

I expect people who are intimately familiar with writing/deploying Spring-Boot-based web apps will instinctively know what to do, but let's not assume all ANNIS admins are like this ;) (I know I'm not.) And [the config sample in the docs](http://korpling.github.io/ANNIS/4.6/user-guide/configuration/index.html) already contains some keys which are not ANNIS-specific but ANNIS users might want to know about them and tweak them, like `server.address` and `server.port`.

So I would argue it would be helpful to have `server.servlet.context-path` there as well. Leave it commented out by default, with a comment explaining what it is / when you might want to set it.

Additionally, it might be a good idea to include hints on how to run Keycloak under a URL prefix too, since people who need the former are likely to need the latter too, and both took me a while to figure out. The decision is more nuanced here ("shouldn't people just read the Keycloak docs?"), but since setting up an OAuth2 provider is basically required for operating an ANNIS v4 installation, I for one very much appreciated [the detailed Keycloak setup guide maintained as part of the ANNIS v4 docs](http://korpling.github.io/ANNIS/4.6/user-guide/configuration/user.html). So I figure it wouldn't hurt to add a bit more to it. It boils down to:

1. You need to run `kc.sh build --http-relative-path /url/prefix` (or use this option with the `--auto-build` option to `kc.sh start`).
2. Make sure you include the prefix when setting up *Valid Redirect URIs*, and remember to modify the setting if the prefix changes.

I don't know how much in the business of helping people configure Keycloak you want to get, but here's the invocation I ended up with:

```sh
kc.sh start --http-enabled true --http-port 5713 --proxy edge --hostname example.com --auto-build --db dev-file --http-relative-path /url/prefix
```

Having a commented example in this moderately complicated vein (Keycloak behind a TLS-terminating reverse proxy) might be helpful. Perhaps with a link to [details on how Keycloak needs the reverse proxy to be set up](https://www.keycloak.org/server/reverseproxy).

(Alternatively, the graphANNIS docs mention a ["local accounts feature"](https://korpling.github.io/graphANNIS/docs/v2.0/rest/auth.html#local-accounts), but the link is broken. If that's a feature that's coming up and would avoid the necessity to set up Keycloak to get a basic ANNIS v4 install running, then extending the Keycloak guide is less of a pressing issue, as it would become an optional, more advanced thing that one doesn't need to set up right away.)

**Comment by thomaskrause** [comment]
The Keycloak part is partly solved by https://github.com/korpling/graphANNIS/pull/235, but we should add the context parameter to the documentation and also make clear how to setup a configuration with anonymous access to all corpora in the ANNIS (not graphANNIS) documentation before <http://korpling.github.io/ANNIS/4.6/user-guide/configuration/user.html> (so we show the easy way first and the more complicated and flexible way as an additional and optional information).

**Comment by thomaskrause** [comment]
The context path is now mentioned in the configuration example. The simplified REST service configuration should be documented when the next graphANNIS release is used in ANNIS: #771

**Comment by dlukes** [comment]
Thank you, good thinking!
