### ISSUE TITLE
Farben und Rauten harmonisieren

### ISSUE THREAD

**Issue by PItchIt** [korpling/ANNIS#78]
![ANNIS_colors](https://f.cloud.github.com/assets/1202453/127022/e66e90c8-6f80-11e2-9498-db801e27a49d.png)
Bei einige Annotationen (bisher Dependenzbäume) ist in der Ausgabe nicht ganz klar, welche Treffer welche Knoten in der Anfrage widerspiegeln.

Es wäre schön, wenn auch im AnnisQL-Feld, die gleichen Farben auftauchen würden. Vielleicht kann man sogar bereits bei der Eingabe farblich die Rauten und die zugehörigen Variablen-Wert-Paare markieren bzw. die unverbundenen Variablen unterstreichen oder so
![ANNIS_colors](https://f.cloud.github.com/assets/1202453/127022/e66e90c8-6f80-11e2-9498-db801e27a49d.png)

**Comment by thomaskrause** [comment]
This should be implemented in most visualizers now and together with #385 (syntax highlighting in AQL editor) assume this as fixed.
