### ISSUE TITLE
Frequencies in corpus explorer

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#79]
The corpus explorer should allow outputting a sorted frequency list (descending) for each annotation name of all annotation values and their frequency in the current corpus. Since this output is likely to be processed/copied to an external program, giving the output in a new tab in a plain text table is preferable (e.g. tab delimited)

**Comment by thomaskrause** [comment]
This is possible with the general frequency query interface. It is quite complicated to keep pre-processed information in sync with the actual corpus and I want to avoid this expensive operations. We might, however, make it easier to explore on-demand frequency query from e.g. the corpus explorer, by adding a link to the examples.
