### ISSUE TITLE
alignment visualization

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#81]
A simple alignment visualization, outputting tokens or another configurable segmentation or annotation value from exactly two texts. The first element name specified in mappings is displayed above and the second below. The middles of both aligned hit areas are centered one over the other, and linear edges are drawn between aligned elements (only between the displayed elements - there is no support e.g. for aligned syntax trees on top of tokens that are being displayed). When a token (or other displayed segmentation or annotation layer) is hovered over, the token, its aligned counterparts and all out/ingoing alignment edges are highlighted. A possible extension is to include alignment edge annotations if available (this could get messy, maybe show as a tooltip on hover over an alignment edge). 

Note that if special alignment edges are implemented in ANNIS (as opposed to the old pointing relations between texts), the visualization would have to be configure to listen to these, or to pointing relations, depending on the corpus.

**Comment by thomaskrause** [comment]
The `sentstructurejs` visualizer should cover the simple cases for alignment with pointing relations. For segmentation, the alignment is already expressed in the grids by covering the same "timeline tokens".
