### ISSUE TITLE
incorrect port in documentation of proxy server?

### ISSUE THREAD

**Issue by gpythomas** [korpling/ANNIS#814]
Shouldn't the port used in the example below be 5712? I couldn't connect to Annis via Apache on my server until I switched the port to 5712 in the Apache configuration file:

```
ProxyPass /annis3-service http://localhost:5711
<location /annis3-service>
SSLRequireSSL
</location>
```

Source: https://korpling.github.io/ANNIS/4.10/user-guide/advanced/backend-frontend-separation.html

**Comment by thomaskrause** [comment]
Thanks for the report. There might be a confusion about which service the documentation is referring to. Port 5712 should be the web-frontend but 5711 should be the REST service. Per default the web-frontend automatically starts the REST service in the background and this should also be on port 5711 . Only if you want to make the REST service available publicly, you should forward port 5711.

**Comment by thomaskrause** [comment]
Reference for myself, the important line in the code is https://github.com/korpling/ANNIS/blob/08a0774a323354e6de7cbe68d8ce336d53b64897/src/main/java/org/corpus_tools/annis/gui/ServiceStarter.java#L211

If the explanation above does not clarify the issue, please re-open it.
