### ISSUE TITLE
Discourse vis is not triggered unless source and destination of PR is in hit

### ISSUE THREAD

**Issue by amir-zeldes** [korpling/ANNIS#83]
In the AOM implementation of ANNIS, the discourse view triggered even if there was only an incoming pointing relation within the hit. Since the move to Salt, both source and destination are required to trigger the visualizer using an 'edge' object in resolver_vis_map. This wouldn't be so bad, except that it is impossible to make sure the discourse visualization is always shown, even if no triggering edge is in the hit context. This is because there is no mappings setting to determine the namespace of the edges to be visualized by the visualization.

I suggest **NOT** fixing the source/destination problem (not compatible with Salt) but instead to introduce a mappings value that determines the edge namespace for the pointing relations to be visualized in the discourse view. This way, the triggering object can be set to NULL so that the visualization is always available, regardless of what the hit area includes.

**Comment by thomaskrause** [comment]
Seem to have been fixed, but now we have a similar bug with #617 in ANNIS 4
